// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcwsacbqmklugvelgegt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjd3NhY2JxbWtsdWd2ZWxnZWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzEwNzUsImV4cCI6MjA3MzgwNzA3NX0.PaL5yhdwCyzT0KQ7EEWjeYWj0sb5W37xV4mc0TmSroo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});